"""add_is_admin_to_users

Revision ID: 9b1c2b84199f
Revises: d61c248a5dfa
Create Date: 2026-05-18 13:26:59.657746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9b1c2b84199f'
down_revision: Union[str, None] = 'd61c248a5dfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
